Gradle fixes (#360)
* Fix error running ./gradlew from command-line.

These changes were generated automatically by running:

    .../android-studio/gradle/gradle-2.10/bin/gradle wrapper

Previously. gradle-wrapper.jar was missing from the repo, so running
"./gradlew" would produce an error:

    Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

* Use secure connection to access gradle repositories (HTTPS).