Added setup wizzard
Refactored launcher activity for setup

Refactored wizzard activity

Added Play Services checks

general fixes

Improved map follow behavior (#352), fixed crt import for some content
providers (#339), fixed missing actionbar on lower APIs (#350), fixed
Google Play services check on startup

Fixed region action mode colors and behavior

Fixed bottom sheet

Gradle fixes (#360)

* Fix error running ./gradlew from command-line.

These changes were generated automatically by running:

    .../android-studio/gradle/gradle-2.10/bin/gradle wrapper

Previously. gradle-wrapper.jar was missing from the repo, so running
"./gradlew" would produce an error:

    Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

* Use secure connection to access gradle repositories (HTTPS).

ignore backups

new versions

sample code to get a widget created

got location into widget textview

refactored widget logic into ServiceWidget

Store list of waypoints per contact and crude distance computation

logs

Added StackView and moving to adaptor based updates

basic setup for the StackView in widget

restructuring progress rendering

first cut working version of widget

added better resources and widget preview

widget UI tweaks

cleaned up log prints

Tweaked widget UI to show geo-coded location

Adding support for incremental waypoint updates

Setting the right topic for remote command requesting other user's waypoints